controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_authenticator:
    path: "/api/auth"
    methods: ['POST']

api_orders:
    path: "api/orders"
    methods: ['GET']

